// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxtxjbvkvktdbxtzdxjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4dHhqYnZrdmt0ZGJ4dHpkeGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTEzNzYsImV4cCI6MjA2NDUyNzM3Nn0.Q8h5YQua0kZz55NAIXjnFG4ib8OeO97oOuRRUmx2IGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);